home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:slug>', views.all_videos, name='all_video'),
    path('post/<int:id>', views.video_detail, name='video_detail'),
    path('result/', views.SearchPage, name='search'),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from embed_video.fields import EmbedVideoField

# Create your models here.
from django.utils.text import slugify


class Video(models.Model):
    name = models.CharField(max_length=100)
    video = EmbedVideoField(null=True,blank=True)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    url = models.URLField(null=True,blank=True)
    image = models.ImageField(upload_to='media/home')
    elsaf = models.ForeignKey('Elsaf', on_delete=models.CASCADE, verbose_name='class', null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        ordering = ('-published_at',)

    def __str__(self):
        return self.name

class Elsaf(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render , redirect
from django.views.generic import ListView

from .models import Video, Elsaf
# Create your views here.

def index(request):
    all_elsaf = Elsaf.objects.all()
    all_videos = Video.objects.all()
    return render(request, 'index.html',{'elsaf': all_elsaf, 'all_videos': all_videos})

def all_videos(request, slug):
    all_elsaf = Elsaf.objects.get(slug=slug)
    all_videos = Video.objects.all()
    return render(request, 'all_videos.html', {'videos' : all_videos, 'elsaf' : all_elsaf})

def video_detail(request, id):
    video_detail = Video.objects.get(id=id)
    all_videos = Video.objects.all()
    context={'video': video_detail, 'videos': all_videos}
    return render(request, 'video_detail.html', context)

def SearchPage(request):
    search = request.GET['search']
    videos = Video.objects.filter(name__icontains=search)
    context = {'video': videos, 'search': search}
    return render(request, 'search.html', context)

home/templates/all_videos.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row kalam">
        <div class="col-12" style="text-align:center;">
            <h1 class="m-4">{{elsaf.name}}</h1>
        </div>
    </div>
    <div class="col d-flex justify-content-center">
        <div class="row">
            {% for i in videos %}
                {% if i.elsaf == elsaf %}
                    <div class="card m-2" width="1rm" style="max-width:353px; max-height:700px;">
                        <img src="{{i.image.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title right">{{i.name}}</h5>
                            <p class="card-text right">{{i.description}}</p>
                            <a href="{% url 'home:video_detail' i.id %}" class="btn btn-primary">عرض المنشور</a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock body %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-top:42px">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="first-slide" src="{% static 'image/22.jpg' %}" alt="First slide" width="512px">
            </div>
            {% for i in all_videos %}
                {% if forloop.counter <= 2 %}
                    <div class="carousel-item">
                        <img class="first-slide" src="{{i.image.url}}" alt="Second slide" width="512px">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>{{i.name}}</h1>
                                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                <p><a class="btn btn-lg btn-primary" href="{% url 'home:video_detail' i.id %}" role="button">Learn more</a></p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <img src="{% static 'image/WhatsApp Image 2021-01-24 at 12.58.34 AM.jpeg' %}" alt="Generic placeholder image" width="250" height="200">
                <div style="margin-bottom:-5px;">
                    <h3 class="text-danger m-3" style="background-color:#EEFF41; height:60px; padding:10px; margin-right:30px; margin-bottom:3px; border-radius:10px;">المرحلة الابتدائية</h3>
                </div>
                <div class="btn-group-vertical">
                    {% for i in elsaf %}
                        {% if i.id <= 7 %}
                        <button type="button" class="btn btn-lg btn-danger"><a href="{% url 'home:all_video' i.slug %}" class="saf">{{i.name}}</a></button>
                        {% endif %}
                    {% endfor %}

                </div>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="rounde-circle" src="{% static 'image/WhatsApp Image 2021-01-24 at 1.08.39 AM (1).jpeg'  %}" alt="Generic placeholder image" width="250" height="200">
                <div style="margin-bottom:-5px;">
                    <h3 class="text-success m-3" style="background-color:#EEFF41; height:60px; padding:10px; margin-right:30px; border-radius:10px;">المرحلة الإعدادية</h3>
                </div>
                <div class="btn-group-vertical">
                    {% for i in elsaf %}
                        {% if i.id > 7 and i.id <= 10 %}
                            <button type="button" class="btn btn-lg btn-success"><a href="{% url 'home:all_video' i.slug %}" class="saf">{{i.name}}</a></button>
                        {% endif %}
                    {% endfor %}
                </div>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="rounde-circle" src="{% static 'image/happy-students-jumping-with-flat-design_23-2147907627.jpg' %}" alt="Generic placeholder image" width="250" height="200">
                <div style="margin-bottom:-5px;">
                    <h2 class="text-primary m-3" style="background-color:#EEFF41; height:60px; padding:10px; margin-right:30px; border-radius:10px;">المرحلة الثانوية</h2>
                </div>
                <div class="btn-group-vertical">
                    {% for i in elsaf %}
                        {% if i.id > 10 %}
                            <button type="button" class="btn btn-lg btn-primary"><a href="{% url 'home:all_video' i.slug %}" class="saf">{{i.name}}</a></button>
                        {% endif %}
                    {% endfor %}
                </div>
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->





        <!-- /END THE FEATURETTES -->
    </div><!-- /.container -->
{% endblock body %}

home/templates/search.html
{% extends "base.html" %}

{% block body %}
    {% for i in video %}
        <div class="col d-flex justify-content-center">
            <div class="row" style="margin-top:70px; margin-bottom:-40px">
                <div class="card m-2" width="1rm" style="max-width:353px; max-height:700px;">
                    <img src="{{i.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title right">{{i.name}}</h5>
                        <p class="card-text right">{{i.description}}</p>
                        <a href="{% url 'home:video_detail' i.slug %}" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <h1>No results found</h1>
    {% endfor %}
{% endblock body %}

home/templates/video_detail.html
{% extends 'base.html' %}
{% load embed_video_tags %}

{% block body %}
 < class="container">
     {% if video.url is None %}
     <div class="col d-flex justify-content-center">
         <div class="row m-5">
             <div style="margin-top:50px; margin-bottom:-50px">
                 {% video video.video '1000x500' %}
             </div>
         </div>
     </div>
     {% else %}
     <div class="row kalam">
         <div class="col-12 " style="text-align:center;">
             <h1 class="m-2"><a href="{{video.url}}" style="" target="_blank">تحميل</a></h1>
         </div>
     </div>
     {% endif %}
 </div>

{% endblock body %}
{% video video.video small %}

templates/base.html
{% load static %}

<html lang="ar-en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'image/WhatsApp Image 2021-01-27 at 7.09.26 AM.jpeg' %}">
    <!-- Fonts -->
    <link rel="preconnect" href="{% static 'https://fonts.gstatic.com' %}">
    <link href="{% static 'fonts/pt-bold-heading.ttf' %}" rel="stylesheet">

    <title>Magic English</title>

    <link rel="canonical" href="{% static 'https://getbootstrap.com/docs/4.1/examples/carousel/' %}">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'style/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'style/style.css' %}" rel="stylesheet">


</head>
<body style="background: rgb(195,34,178); background: radial-gradient(circle, rgba(195,34,178,1) 0%, rgba(253,187,45,1) 100%);">

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <h1><a class="navbar-brand m-2" href="{% url 'home:index' %}" style="font-size:34px"><b>Magic English</b></a></h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home:index' %}" style="margin:5px">Home <span class="sr-only" style="margin:5px;">(current)</span></a>
                </li>
                <li>
                    <div class="dropdown" style="margin:5px">
                        <button class="btn btn-danger dropdown-toggle" type="button" data-toggle="dropdown">المرحلة الابتدائية<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='primary-stage-1' %}">الصف الاول </a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='primary-stage-2' %}">لصف الثاني</a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='primary-stage-3' %}">الصف الثالث</a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='primary-stage-4' %}">الصف الرابع</a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='primary-stage-5' %}">الصف الخامس</a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='primary-stage-6' %}">الصف السادس</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <div class="dropdown" style="margin:5px">
                        <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">المرحلة الإعدادية<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='preparatory-stage-1' %}">الصف الاول</a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='preparatory-stage-2' %}">لصف الثاني</a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='preparatory-stage-3' %}">الصف الثالث</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <div class="dropdown" style="margin:5px">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">المرحلة الثانوية<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='secondary-stage-1' %}">الصف الاول</a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='secondary-stage-2' %}">لصف الثاني</a></li>
                            <li style="text-align:center"><a href="{% url 'home:all_video' slug='secondary-stage-3' %}">الصف الثالث</a></li>
                        </ul>
                    </div>
                </li>
                <!-- Example split danger button -->
            </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'home:search' %}" >
            <input class="form-control mr-sm-2" type="search" name="search" style="margin:5px">
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit" style="margin:5px;"> Search </button>
        </form>
        </div>
    </nav>
</header>

<main role="main">

    {% block body %}


    {% endblock body %}
    <!-- FOOTER -->
    <hr class="featurette-divider">
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p> جميع الحقوق محفوظة &copy; Magic English 2021</p>
    </footer>
</main>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'https://code.jquery.com/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static 'js/holder.min.js' %}"></script>
<!-- Optional JavaScript; choose one of the two! -->
</body>
</html>

<!-- style="background-color:#880E4F; width:300px;height:50px"-->